name: my_ecommerce_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'




dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  carousel_slider: ^4.1.1
  cached_network_image: ^3.2.1
  shimmer: ^2.0.0
  provider: ^6.0.3
  http: ^0.13.5
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.0.9
  awesome_dialog: ^3.0.2
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.1
  cloud_firestore: ^3.5.0
  firebase_storage: ^10.3.10
  shared_preferences: ^2.0.15
  flutter_credit_card: ^3.0.4
  settings_ui: ^2.0.2
  firebase_core_desktop: ^1.0.2
  firedart: ^0.9.0+1
  desktop_window: ^0.4.0
  fluent_ui: ^4.0.1
#  window_size:
#    git:
#      url: git://github.com/google/flutter-desktop-embedding.git
#      path: plugins/window_size



dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/app/
    - assets/auth/
    - assets/orderConfirm/



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/applogo1.jpg"
#  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app/applogo1.jpg"
#    background_color: "#hexcode"
#    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/app/applogo1.jpg"
#    icon_size: 48 # min:48, max:256, default: 48